### ISSUE TITLE
gp_plumb changes the working directory

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#77] opened 2020-05-09 11:19 UTC
Should it change back to the original e.g. with:

```r
old = setwd("app")
# ... plumb
setwd(old)
```

**Comment by layik** [comment] 2020-05-11 17:58
So this should not be happening and it is not a bug. The way `gp_plumb` works, in my opinion should never does stuff like this. It should always be the user who would need to be in a `gp` project directory. Happy to remove both references to the relevant function.

The function itself could be exported as a helper function, users may or may not use it.

**Comment by Robinlovelace** [comment] 2020-05-12 05:35
If there's a setting like `cd = FALSE` by default, it could `cd` with a message but by default only work if you're already in an app directory.

**Comment by layik** [comment] 2020-05-12 08:25
Just to be clear, if I remove the offending line, all that is going to happen is a warning to user that `please be in a gp dir`. The alternative would be to provide a `geoplumber` path which I think is messy. So example would be `usethis::use_package("stats19", path="/some/path")`.

As for `cd = FALSE` or other work arounds, a couple of things but main point is I have not worked out how to overcome running code *after* a `plumber` blocking thread is "killed". So I can reset user pref after `plumber` is done. Because if user says `cd = FALSE` they might as well just cd into a project and as all they will get is the warning.

Slightly related to #82

**Comment by layik** [comment] 2020-05-12 08:26
So it is a matter of package strategy as well.

**Comment by layik** [comment] 2020-05-14 09:01
Should not do so now. Closing.

**Closed by layik** 2020-05-14 09:01 UTC
Labels: enhancement
